将输出用类表达
syhanjin/AutoMirror pull request #2
Opened 2024-10-17 10:30 UTC by syhanjin

2024-10-17 10:32 UTC, syhanjin commented
忘记写了，取消了函数的返回值

2024-10-17 11:49 UTC, Origami404 requested changes
1. 如果取消了返回值, 那感觉这样改就比较脱裤子放屁了 -- 合并二者本来是为了避免同样的信息在日志输出和结果收集两个地方写两次
2. 继承结构很奇怪, 直接把每个子类需要的东西在父类里写出来然后再用继承改感觉完全是乱来, 而且感觉这样你没有分清类对象上的变量和对象上的变量, 按 OOP 思路组织代码的话应该只把 code 放父类然后靠 `__init__` 往上传. 同时可以看看 dataclass 之类的东西.

2024-10-17 13:54 UTC, syhanjin commented
有一说一，用搞个类进行输出这个方式感觉就有点抽象（在改了在改了）

2024-10-20 10:12 UTC, Origami404 commented
我还是觉得很抽象... 没有返回值的话不如直接恢复到 logging + f-string 方案好了

2024-10-20 10:14 UTC, Origami404 commented
不需要返回值的话直接把 return 那行删掉之后, 这个输出的行为就没有代码重复了, 就没必要规范了

2024-10-20 10:14 UTC, syhanjin commented
> 不需要返回值的话直接把 return 那行删掉之后, 这个输出的行为就没有代码重复了, 就没必要规范了

现在有返回值了

2024-10-20 10:15 UTC, syhanjin commented
我在创建那个类的时候进行了日志输出，

2024-10-29 12:51 UTC, closed without merging