单独封装配置文件读取和校验
syhanjin/AutoMirror pull request #5
Opened 2024-10-29 15:23 UTC by syhanjin

2024-10-29 15:36 UTC, Origami404 requested changes

2024-10-29 15:36 UTC, Origami404 commented on src/automirror/configs.py
> +class Config:
这个 Config 为什么要按类对象用?

2024-10-29 15:36 UTC, Origami404 commented on src/automirror/configs.py
> +    target_client: AsyncClient
如果这个类并不是只代表一个配置文件, 而是还代表了某次同步的一些中间变量的话, 建议不要叫 Config

2024-10-29 15:36 UTC, Origami404 commented on src/automirror/main.py
> +
空白删一下, 过一下格式化器

2024-10-30 00:17 UTC, syhanjin commented on src/automirror/configs.py
> +    target_client: AsyncClient
嗯，那一般这种叫什么，我感觉这个也没必要分开

2024-10-30 03:02 UTC, merged